create table if not exists public.invoice_line_items (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.invoices(id) on delete cascade,
  description text not null,
  quantity numeric,
  unit_price numeric,
  vat_rate numeric,
  line_total numeric,
  confidence integer not null default 0 check (confidence between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists invoice_line_items_invoice_id_idx on public.invoice_line_items (invoice_id);

alter table public.invoice_line_items enable row level security;

create policy "OCR5 anon can insert invoice line items" on public.invoice_line_items
for insert to anon with check (true);

create policy "OCR5 anon can read invoice line items" on public.invoice_line_items
for select to anon using (true);
